name: Deploy Static HTML

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

    - name: Deploy to gh-pages
      run: |
        # Ensure the gh-pages branch exists
        git checkout --orphan gh-pages
        
        # Remove old files except the static files directory (e.g., 'static' or 'dist')
        git rm -rf . --ignore-unmatch || true
        
        # Copy static files (adjust if your files are in a specific folder)
        cp -r ./ ./ || true  # Assuming your files are already in the root

        # Add, commit, and push changes
        git add .
        git commit -m "Deploy static HTML site"
        git push -f origin gh-pages
