name: Deploy Static HTML

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy with Git
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git push origin gh-pages
