name: Deploy Static HTML

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

    - name: Deploy to gh-pages
      run: |
        # Ensure the gh-pages branch exists
        git checkout gh-pages || git checkout --orphan gh-pages

        # Clean the branch but preserve .git folder
        ls -A | xargs rm -rf || true
        
        # Copy files from the main branch
        git checkout main -- .

        # Add, commit, and push changes
        git add .
        git commit -m "Deploy static HTML site" || echo "No changes to commit"
        git push -f origin gh-pages
